name: Update TryHackMe Badge

on:
  schedule:
    - cron: "0 12 * * *"   # runs once a day at 12:00 UTC
  workflow_dispatch:       # lets you run it manually

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update badge
        uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: darkciphr
